base_url = "https://docs-levxyca.netlify.app/"
title = "Docs"
compile_sass = true
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
logo = "/logo.png"
favicon = "/favicon.ico"
